name: CI Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install & Build
        run: |
          npm ci
          npm run build-library-prod

      - name: Build Github Pages
        run: |
          npm run create-deployment

      - name: Publish GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.out
        if: ${{ github.ref == 'refs/heads/main' }}
