name: CI 2 NPM

on:
  push:
    tags:
      - "v*"
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install & Build
        run: |
          npm ci
          npm run build-library-prod

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
        run: |
          npm publish ./dist/sc-tailwind
